"""Fairness audit: does resolution quality vary by customer segment in a way
that suggests the system (or the historical process it learned from) treats
some customers worse than others?

Reads the `history` block already present on every development ticket
(csat_rating, resolution_time_minutes, escalated, first_contact_resolution)
-- outcomes from the historical process, not from this system -- and groups
them by channel, customer tier, language fluency and region. This is a
description of the data the classifier trains on, not a claim about the
pipeline's own behaviour; a segment gap here is a reason to look at
retrieval/classification performance for that segment specifically, not
evidence on its own that the pipeline is unfair.

Writes docs/fairness_audit.md. Run with `python -m scripts.fairness_audit`.
"""
from __future__ import annotations
import json
import os
import statistics as stats

DATA_DIR = os.getenv("DATA_DIR", "./data")
OUTPUT_PATH = os.path.join("docs", "fairness_audit.md")

DIMENSIONS = ["channel", "customer_tier", "language_fluency", "customer_region"]

# A gap larger than this between a segment and the overall mean is called out
# explicitly rather than left for a reader to notice in a table.
CSAT_FLAG_POINTS = 0.3          # on a 1-5 scale
ESCALATION_FLAG_POINTS = 0.10   # 10 percentage points


def _segment_stats(tickets: list[dict], dimension: str) -> dict[str, dict]:
    groups: dict[str, list[dict]] = {}
    for t in tickets:
        key = str(t.get(dimension) or "unknown")
        groups.setdefault(key, []).append(t)

    out = {}
    for key, group in sorted(groups.items()):
        histories = [t["history"] for t in group if t.get("history")]
        n = len(group)
        out[key] = {
            "n": n,
            "mean_csat": round(stats.mean(h["csat_rating"] for h in histories), 2) if histories else None,
            "mean_resolution_minutes": round(stats.mean(h["resolution_time_minutes"] for h in histories), 1) if histories else None,
            "escalation_rate": round(sum(1 for h in histories if h["escalated"]) / len(histories), 4) if histories else None,
            "fcr_rate": round(sum(1 for h in histories if h["first_contact_resolution"]) / len(histories), 4) if histories else None,
        }
    return out


def audit(tickets_path: str) -> dict:
    with open(tickets_path, encoding="utf-8") as f:
        tickets = json.load(f)

    all_histories = [t["history"] for t in tickets if t.get("history")]
    overall = {
        "n": len(tickets),
        "mean_csat": round(stats.mean(h["csat_rating"] for h in all_histories), 2),
        "mean_resolution_minutes": round(stats.mean(h["resolution_time_minutes"] for h in all_histories), 1),
        "escalation_rate": round(sum(1 for h in all_histories if h["escalated"]) / len(all_histories), 4),
    }

    report: dict = {"overall": overall, "dimensions": {}, "flags": []}
    for dimension in DIMENSIONS:
        segment_stats = _segment_stats(tickets, dimension)
        report["dimensions"][dimension] = segment_stats
        for key, seg in segment_stats.items():
            if seg["mean_csat"] is not None and abs(seg["mean_csat"] - overall["mean_csat"]) >= CSAT_FLAG_POINTS:
                report["flags"].append(
                    f"{dimension}={key}: CSAT {seg['mean_csat']} vs overall {overall['mean_csat']} "
                    f"({'below' if seg['mean_csat'] < overall['mean_csat'] else 'above'} by "
                    f"{abs(seg['mean_csat'] - overall['mean_csat']):.2f} points, n={seg['n']})"
                )
            if seg["escalation_rate"] is not None and abs(seg["escalation_rate"] - overall["escalation_rate"]) >= ESCALATION_FLAG_POINTS:
                report["flags"].append(
                    f"{dimension}={key}: escalation rate {seg['escalation_rate']:.1%} vs overall "
                    f"{overall['escalation_rate']:.1%} "
                    f"({'higher' if seg['escalation_rate'] > overall['escalation_rate'] else 'lower'} by "
                    f"{abs(seg['escalation_rate'] - overall['escalation_rate']):.1%}, n={seg['n']})"
                )
    return report


def _render_table(segment_stats: dict[str, dict]) -> str:
    lines = ["| Segment | n | Mean CSAT | Mean resolution (min) | Escalation rate | FCR rate |",
             "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for key, seg in segment_stats.items():
        lines.append(
            f"| {key} | {seg['n']} | {seg['mean_csat']} | {seg['mean_resolution_minutes']} | "
            f"{seg['escalation_rate']:.1%} | {seg['fcr_rate']:.1%} |"
        )
    return "\n".join(lines)


def render_markdown(report: dict, tickets_path: str) -> str:
    overall = report["overall"]
    parts = [
        "# Fairness audit",
        "",
        f"Generated by `python -m scripts.fairness_audit` from `{os.path.normpath(tickets_path)}` "
        f"({overall['n']} tickets). Every number below comes from the `history` "
        "block already recorded on each development ticket -- the outcome of the "
        "historical, human-run process, not of this system.",
        "",
        f"**Overall:** mean CSAT {overall['mean_csat']}/5, mean resolution time "
        f"{overall['mean_resolution_minutes']} minutes, escalation rate "
        f"{overall['escalation_rate']:.1%}.",
        "",
    ]
    for dimension in DIMENSIONS:
        parts.append(f"## By {dimension.replace('_', ' ')}")
        parts.append("")
        parts.append(_render_table(report["dimensions"][dimension]))
        parts.append("")

    parts.append("## Flagged gaps")
    parts.append("")
    if report["flags"]:
        parts.append(
            f"Segments differing from the overall mean by at least {CSAT_FLAG_POINTS} CSAT "
            f"points or {ESCALATION_FLAG_POINTS:.0%} escalation-rate points:"
        )
        parts.append("")
        for flag in report["flags"]:
            parts.append(f"- {flag}")
    else:
        parts.append("No segment differs from the overall mean by more than the flag threshold.")
    parts.append("")
    parts.append(
        "**Reading this table.** A gap here describes the historical process the "
        "development data was drawn from, before this system existed. It is a "
        "worthwhile thing to re-measure against this system's own routing and "
        "resolution outcomes once enough live decisions have accumulated in the "
        "decision log -- see `src/logging_store.py` -- rather than treated as a "
        "verdict on the pipeline itself."
    )
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    tickets_path = os.path.join(DATA_DIR, "development_tickets.json")
    report = audit(tickets_path)
    markdown = render_markdown(report, tickets_path)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"Wrote {OUTPUT_PATH}")
    print(f"Overall: {report['overall']}")
    print(f"Flags: {len(report['flags'])}")
    for flag in report["flags"]:
        print(f"  - {flag}")


if __name__ == "__main__":
    main()
